name: Deploy Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH key
  run: |
    echo "${{ secrets.ETL_KEY }}" > $HOME/etl-key.pem
    chmod 600 $HOME/etl-key.pem

    - name: Deploy to EC2
  run: |
    ssh -o StrictHostKeyChecking=no -i $HOME/etl-key.pem ubuntu@18.226.34.255 'cd /home/ubuntu/restaurant_sales_etl_project && ./deploy.sh'